version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: vue
      POSTGRES_USER: vue
      POSTGRES_DB: vue
    ports:
      - '5432:5432'

  app:
    build:
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://vue:vue@db:5432/vue
        VITE_APP_BACKEND_URL: http://localhost:3000
    ports:
      - '3000:3000'
      - '4173:4173'
      - '4174:4174'
    command: bun run start
    links:
      - db
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://vue:vue@db:5432/vue
      PORT: 3000
      VITE_APP_BACKEND_URL: http://localhost:3000
